cabal-version: 3.0
name:          foobar
version:       2.0.0
synopsis:      A simple bar, launcher, control center, and notification daemon.
build-type:    Simple

common warnings
    ghc-options: -Wall

executable foobar
    import:           warnings
    main-is:          Main.hs
    build-depends:    base,
                      haskell-gi,
                      haskell-gi-base,
                      gi-gio,
                      gi-glib,
                      gi-gtk4,
                      gi-gdk4,
                      gi-foobar,
                      declarative-gtk,
                      optics-core,
                      text,
                      filepath,
                      directory
    other-modules:    Foobar.Application,
                      Foobar.Models.Config,
                      Foobar.Services.Config
    default-language: Haskell2010
